language: python
python:
- "3.4"
- "3.5"
- "3.6"
virtual_env:
  system_site_packages: true
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
  pytest --cov=cnab240
after_success:
  coveralls
deploy:
  provider: pypi
  user: trustcode
  password:
    secure: pZcdJ+vMVezbi2IM9Ddpv7cBkWPRhOwBQni595lXAZJWD2fdnT+xFPrCz590G733egcKbtKQFwTuHVVvmj2ROGIwWlpbvhpawYrC8mv3OHAPBFdsL9Ejkr836P92JHoLf3N9Cvp7kqUq1CufjbRJC58MNymsp6g4zC+2g6RMmHyfOiVxizEwzkG0QP0C1dM5q1BJU4okOJ6Sk7LN5YDAXLTiVPNUswrggkxyriDxzgRF49LysHZZyAk2KHwYMnVm6zscVpI34PNhgrjX91Qb1+KA6n8IdtbLB5d21drJWznq0N4Fx6b4lSNugwRJtJDPljtsqKPM2bDHNpXa8HXVG9+X6A8LmpOmiNmqneQiFezf7qUPRvcOoEakJaIyRVBSeB/DNlmedHz8y8Zyw7tI+1GY/y6oTKQtqWwjrAlid4d+Zgu7lZBuNtR7v5ywT4SjyZLXHaA2rmBbFPEh+W0BsEVg2vdtsMbVQyxtlaadGDVfej5xS6pymHOIk+Jv6u8Vk78vnFGVw5rKpSl0i1UBbRjEPzYpwseraLcWVgPEFPxSzBPFaltcmexWqTN5ECjtskc9GxJi03y1Aawn9lzdx9aA0xnKbdSFRdirlias89+i/OXYH/ojqIJQgn38qWxhgOubRwO9w3QIeRdR6es4F2j1ZmJbOxSuCqjvOhxEzzc=
  on:
    branch: master3
  distributions: bdist_wheel
